### ISSUE TITLE
Error in run.sh

### ISSUE THREAD

**Issue by ash22194** [rohitgirdhar/ActionVLAD#11]
In run.sh

**TMPDIR="/tmp/ActionVLAD-DEMO/"** and **LIST_DIR=$TMPDIR/lists/** leads to invalid path-names. Changing it to **TMPDIR="/tmp/ActionVLAD-DEMO"** and **LIST_DIR=$TMPDIR/lists** would fix it

In get_models.sh

**KMEANS_DIR=models/kmeans-init/** leads to invalid pathnames. Changing it to **KMEANS_DIR=models/kmeans-init** would fix the issue

**Comment by rohitgirdhar** [comment]
I am not sure why is it invalid. From the [Single Unix specification (version 3), base definitions §3.266 pathname](http://www.opengroup.org/onlinepubs/009695399/): “Multiple successive slashes are considered to be the same as one slash.” I've tested the code and it worked on CentOS at least. Please feel free to re-open in case this is still an issue.
