### ISSUE TITLE
Extract feature

### ISSUE THREAD

**Issue by Guoleming** [rohitgirdhar/ActionVLAD#14]
How to extract  features of actionvlad

**Comment by rohitgirdhar** [comment]
Please refer to the [demo](https://github.com/rohitgirdhar/ActionVLAD/tree/master/demo). You can change the layer in [`ext_feats.py`](https://github.com/rohitgirdhar/ActionVLAD/blob/master/demo/ext_feats.sh).

**Comment by Guoleming** [comment]
why all my  actionvlad feature's value are 0 ?

**Comment by Guoleming** [comment]
Thanks for your anwser, but i have met a question.

why  my actionvald features' value are 0 ? 
[[-0. -0. -0. ... -0. -0. -0.]]
