### ISSUE TITLE
when i exec "git clone git@github.com:tensorflow/tensorflow.git" come up a error

### ISSUE THREAD

**Issue by daixiangzi** [rohitgirdhar/ActionVLAD#18]
error report:
(tf_v0.12.0rc0) root@daixiangzi:/home/zi/桌面/deecamp/ActionVLAD# git clone git@github.com:tensorflow/tensorflow.git
正克隆到 'tensorflow'...
Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.

**Comment by rohitgirdhar** [comment]
You can try to use https path to clone TF (https://github.com/tensorflow/tensorflow.git).
Updated the README.

**Comment by daixiangzi** [comment]
why in this https://github.com/tensorflow/tensorflow.git) no have your provide tensorflow version about 0.12
