### ISSUE TITLE
netvlad_initCenters

### ISSUE THREAD

**Issue by theuselesscorporation** [rohitgirdhar/ActionVLAD#19]
Where can I get these files 

netvlad_initCenters models/Experiments/001_VGG_RGB_HMDB_netvlad_stage1/Features/imnet_conv5_kmeans64.pkl

and how do I generate my own netvlad?

Thanks
Rick

**Comment by rohitgirdhar** [comment]
Please look at the [`get_models.sh`](https://github.com/rohitgirdhar/ActionVLAD/blob/08d3d65301940991e0a0cdca2c0534edf6749f41/get_models.sh#L28). For training your own model, please read the [README](https://github.com/rohitgirdhar/ActionVLAD#training).

**Comment by theuselesscorporation** [comment]
Hi Rohit!! thanks for your response.

For training the ReadMe says to run the script  001_VGG_RGB_HMDB_netvlad_stage1.sh  for example.
But to run the script I need to have 'imnet_conv5_kmeans64.pkl' file.

I would like to know how can I generate my own file, say for another dataset?

Thanks
