### ISSUE TITLE
question related to issue 19

### ISSUE THREAD

**Issue by theuselesscorporation** [rohitgirdhar/ActionVLAD#20]
Hi Rohit!! thanks for your response.

For training the ReadMe says to run the script 001_VGG_RGB_HMDB_netvlad_stage1.sh for example.
But to run the script I need to have 'imnet_conv5_kmeans64.pkl' file.

I would like to know how can I generate my own file, say for another dataset?

Thanks

**Comment by rohitgirdhar** [comment]
As I pointed out in that issue, the link is in the `get_models.sh`: https://cmu.box.com/shared/static/9rq9gy0sjwyr2wxm4kt1kd4ogbzpts77.pkl

Please see the training instructions on how to generate it on your own cluster centers. (`001_VGG_RGB_HMDB_netvlad_feats_for_clustering.sh` and `001_VGG_RGB_HMDB_netvlad_cluster.sh`)
