### ISSUE TITLE
meta file for pretrained model

### ISSUE THREAD

**Issue by gaosh** [rohitgirdhar/ActionVLAD#21]
Hi, 
I want to use your pretrained model on pytorch. Converting tensorflow model to pytorch model require both meta file and weight file. Could you provide the meta file for your saved model? Any suggestions are welcome.

Thanks

**Comment by rohitgirdhar** [comment]
I would suggest just loading the TF model file (by [inspecting the checkpoint](https://github.com/tensorflow/tensorflow/blob/1095ed8fe6808a70edb66d7970e9462db791e690/tensorflow/python/tools/inspect_checkpoint.py)), and writing it out into your favorite format.
