### ISSUE TITLE
Evaluate on ucf101 dataset

### ISSUE THREAD

**Issue by 66wzy** [rohitgirdhar/ActionVLAD#22]
Hi, I try to reproduce the results achieved in your paper on ucf101 dataset. And I get the trained model by `get_models.sh`. The rgb  stream works well, about 82.7%, as your answer in question#2. But the flow stream only has 44%.
I rewrote the `001_VGG_Flow_HMDB_netvlad_eval.sh` file: I use the model you given as `--checkpoint_path`; change  `--dataset_name` to ucf101; and change `--ncrops` to 1.
Did I make mistake.

**Comment by rohitgirdhar** [comment]
That is odd. My guess is it might be due to different flow encodings. Did you use the flow computations as in [this work](http://yjxiong.me/others/action_recog/)? You could also maybe try training the model on your flow data

**Comment by icyzhang0923** [comment]
Could you tell me how to transfer the caffe models of flow stream pre-trained on UCF101 to TensorFlow models?

**Comment by 66wzy** [comment]
@icyzhang0923 Sorry for late. I transferred model by [caffe-tensorflow tool](https://github.com/ethereon/caffe-tensorflow)

**Comment by icyzhang0923** [comment]
I transferred model from .caffemodel to .npy, then could you tell me how to use .npy for ActionVLAD，some restore process?
