### ISSUE TITLE
docker to avoid dependencies errors

### ISSUE THREAD

**Issue by fninaparavecino** [rohitgirdhar/ActionVLAD#23]
Great work, and I'd like to test it but it is giving errors based on dependencies for cudnn5. I got the same error as https://github.com/rohitgirdhar/ActionVLAD/issues/12

cudnn nowadays is on 7.2, even if I installed the cudnn 5.1 still is not solving the issue. In order to avoid dependencies errors for versioning, could you guys provide a dockerfile? That can solve a lot of the issues.

**Comment by rohitgirdhar** [comment]
Thanks for your interest. Unfortunately it's hard to keep things updated with the latest library versions and docker file would a good idea. Contributions are welcome!

**Comment by fninaparavecino** [comment]
I have created the dockerfile but it is set to work with python3. And I keep getting the following error: 
`Dropout is not being applied to the model to be consistent with original release of the code. Due to an issue it was not enabled in the original release. Please uncomment lines in nets/nets_factory.py to enable the dropout.
WARNING:tensorflow:From eval_image_classifier.py:278 in main.: streaming_recall_at_k (from tensorflow.contrib.metrics.python.ops.metric_ops) is deprecated and will be removed after 2016-11-08.
Instructions for updating:
Please use `streaming_sparse_recall_at_k`, and reshape labels from [batch_size] to [batch_size, 1].`


I have uncommented the lines in nets/nets_factory.py but stills no luck running the demo.

Any ideas?

**Comment by rohitgirdhar** [comment]
Can you please paste the full error message? I don't see an error message here, these are just warnings.

**Comment by fninaparavecino** [comment]
It is the same error as before.

`Input #0, mov,mp4,m4a,3gp,3g2,mj2, from 'soccer10.mp4':
  Metadata:
    major_brand     : isom
    minor_version   : 512
    compatible_brands: isomiso2mp41
    encoder         : Lavf58.3.100
  Duration: 00:00:00.45, start: 0.000000, bitrate: 72731 kb/s
    Stream #0:0(und): Video: mpeg4 (Simple Profile) (mp4v / 0x7634706D), yuv420p, 5120x3072 [SAR 1:1 DAR 5:3], 72715 kb/s, 20 fps, 20 tbr, 90k tbn, 20 tbc (default)
    Metadata:
      handler_name    : VideoHandler
[swscaler @ 0x2ad8000] deprecated pixel format used, make sure you did set range correctly
Output #0, image2, to '/tmp/ActionVLAD-DEMO//frames/image_%05d.jpg':
  Metadata:
    major_brand     : isom
    minor_version   : 512
    compatible_brands: isomiso2mp41
    encoder         : Lavf56.40.101
    Stream #0:0(und): Video: mjpeg, yuvj420p(pc), 5120x3072 [SAR 1:1 DAR 5:3], q=2-31, 200 kb/s, 20 fps, 20 tbn, 20 tbc (default)
    Metadata:
      handler_name    : VideoHandler
      encoder         : Lavc56.60.100 mjpeg
Stream mapping:
  Stream #0:0 -> #0:0 (mpeg4 (native) -> mjpeg (native))
Press [q] to stop, [?] for help
frame=    9 fps=6.5 q=1.0 Lsize=N/A time=00:00:00.45 bitrate=N/A    
video:14318kB audio:0kB subtitle:0kB other streams:0kB global headers:0kB muxing overhead: unknown
I tensorflow/stream_executor/dso_loader.cc:128] successfully opened CUDA library libcublas.so locally
I tensorflow/stream_executor/dso_loader.cc:128] successfully opened CUDA library libcudnn.so locally
I tensorflow/stream_executor/dso_loader.cc:128] successfully opened CUDA library libcufft.so locally
I tensorflow/stream_executor/dso_loader.cc:128] successfully opened CUDA library libcuda.so.1 locally
I tensorflow/stream_executor/dso_loader.cc:128] successfully opened CUDA library libcurand.so locally
INFO:tensorflow:Using file /tmp/ActionVLAD-DEMO//lists//test_split1.txt
INFO:tensorflow:Scale of 0 disables regularizer.
INFO:tensorflow:BGR flipping stream 0
INFO:tensorflow:Assuming the batch is full of RGB images, and BGR flipped
INFO:tensorflow:Performing eval pre-processing
INFO:tensorflow:Randomly initializing the (64, 512) netvlad cluster centers
INFO:tensorflow:Scale of 0 disables regularizer.
INFO:tensorflow:Scale of 0 disables regularizer.
INFO:tensorflow:Scale of 0 disables regularizer.
Dropout is not being applied to the model to be consistent with original release of the code. Due to an issue it was not enabled in the original release. Please uncomment lines in nets/nets_factory.py to enable the dropout.
WARNING:tensorflow:From eval_image_classifier.py:278 in main.: streaming_recall_at_k (from tensorflow.contrib.metrics.python.ops.metric_ops) is deprecated and will be removed after 2016-11-08.
Instructions for updating:
Please use `streaming_sparse_recall_at_k`, and reshape labels from [batch_size] to [batch_size, 1].
Traceback (most recent call last):
  File "eval_image_classifier.py", line 357, in <module>
    tf.app.run()
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/platform/app.py", line 43, in run
    sys.exit(main(sys.argv[:1] + flags_passthrough))
  File "eval_image_classifier.py", line 282, in main
    for name, value in names_to_values.iteritems():
AttributeError: 'dict' object has no attribute 'iteritems'
Traceback (most recent call last):
  File "get_class.py", line 7, in <module>
    with h5py.File(sys.argv[1], 'r') as fin, open(sys.argv[2], 'r') as fin2:
  File "/usr/local/lib/python3.5/dist-packages/h5py/_hl/files.py", line 394, in __init__
    swmr=swmr)
  File "/usr/local/lib/python3.5/dist-packages/h5py/_hl/files.py", line 170, in make_fid
    fid = h5f.open(name, flags, fapl=fapl)
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "h5py/h5f.pyx", line 85, in h5py.h5f.open
OSError: Unable to open file (unable to open file: name = '/tmp/ActionVLAD-DEMO//feats.h5', errno = 2, error message = 'No such file or directory', flags = 0, o_flags = 0)
`

**Comment by rohitgirdhar** [comment]
The error is here:

```
AttributeError: 'dict' object has no attribute 'iteritems'
```

It's because you're using python3, where `iteritems` has been renamed to `items`. Can you try to run with python2? Or you could also try to make the required modifications to make it compatible with python3.

**Comment by fninaparavecino** [comment]
So... I created a new container with python2, and it went further. Now, I got memory warning, how much GPU memory is needed for the demo? I have a GTX 1080Ti See below the warning:

Dropout is not being applied to the model to be consistent with original release of the code. Due to an issue it was not enabled in the original release. Please uncomment lines in nets/nets_factory.py to enable the dropout.
WARNING:tensorflow:From eval_image_classifier.py:278 in main.: streaming_recall_at_k (from tensorflow.contrib.metrics.python.ops.metric_ops) is deprecated and will be removed after 2016-11-08.
Instructions for updating:
Please use `streaming_sparse_recall_at_k`, and reshape labels from [batch_size] to [batch_size, 1].
INFO:tensorflow:Evaluating models/PreTrained/ActionVLAD-pretrained/hmdb51/rgb/split1.ckpt
I tensorflow/core/common_runtime/gpu/gpu_device.cc:885] Found device 0 with properties: 
name: GeForce GTX 1080 Ti
major: 6 minor: 1 memoryClockRate (GHz) 1.582
pciBusID 0000:03:00.0
Total memory: 10.92GiB
Free memory: 10.76GiB
I tensorflow/core/common_runtime/gpu/gpu_device.cc:906] DMA: 0 
I tensorflow/core/common_runtime/gpu/gpu_device.cc:916] 0:   Y 
I tensorflow/core/common_runtime/gpu/gpu_device.cc:975] Creating TensorFlow device (/gpu:0) -> (device: 0, name: GeForce GTX 1080 Ti, pci bus id: 0000:03:00.0)
INFO:tensorflow:Doing batch 0/1
W tensorflow/core/common_runtime/bfc_allocator.cc:217] Ran out of memory trying to allocate 3.94GiB. The caller indicates that this is not a failure, but may mean that there could be performance gains if more memory is available.
INFO:tensorflow:Writing out features to /tmp/ActionVLAD-DEMO//feats.h5
/usr/local/lib/python2.7/dist-packages/h5py/_hl/dataset.py:313: H5pyDeprecationWarning: dataset.value has been deprecated. Use dataset[()] instead.
  "Use dataset[()] instead.", H5pyDeprecationWarning)
Detected action: jump

Thanks for the help!

**Comment by fninaparavecino** [comment]
Req merge https://github.com/rohitgirdhar/ActionVLAD/pull/27 to have docker on your repo. You can change the git path to point to your :)... Thanks again!

**Comment by rohitgirdhar** [comment]
I think you an ignore the memory warnings, as it says. Glad it worked and thanks for the docker file!
