### ISSUE TITLE
tensorflow.python.framework.errors_impl.InternalError: Unable to get element from the feed as bytes.

### ISSUE THREAD

**Issue by haoyangwu** [rohitgirdhar/ActionVLAD#3]
Thank you for developing such a cool algorithm for action detection. It is really pioneer work since there aren't many out there.
I tried to run a demo.mp4 video in /data by running:
bash run.sh /Users/wuhaoyang/vlad/data/demo.mp4

But I came across a very tricky problem, here is what the terminal says:
Using /tmp/ActionVLAD-DEMO for storing temporary data. WILL BE DELETED.
ffmpeg version 3.3.1 Copyright (c) 2000-2017 the FFmpeg developers
  built with Apple LLVM version 8.1.0 (clang-802.0.42)
  configuration: --prefix=/usr/local/Cellar/ffmpeg/3.3.1 --enable-shared --enable-pthreads --enable-gpl --enable-version3 --enable-hardcoded-tables --enable-avresample --cc=clang --host-cflags= --host-ldflags= --enable-libmp3lame --enable-libx264 --enable-libxvid --enable-opencl --disable-lzma --enable-vda
  libavutil      55. 58.100 / 55. 58.100
  libavcodec     57. 89.100 / 57. 89.100
  libavformat    57. 71.100 / 57. 71.100
  libavdevice    57.  6.100 / 57.  6.100
  libavfilter     6. 82.100 /  6. 82.100
  libavresample   3.  5.  0 /  3.  5.  0
  libswscale      4.  6.100 /  4.  6.100
  libswresample   2.  7.100 /  2.  7.100
  libpostproc    54.  5.100 / 54.  5.100
Input #0, mov,mp4,m4a,3gp,3g2,mj2, from '/Users/wuhaoyang/vlad/data/demo.mp4':
  Metadata:
    major_brand     : mp42
    minor_version   : 0
    compatible_brands: mp41isom
  Duration: 00:00:07.40, start: 0.000000, bitrate: 5315 kb/s
    Stream #0:0(und): Video: h264 (Main) (avc1 / 0x31637661), yuv420p, 1280x720 [SAR 1:1 DAR 16:9], 5313 kb/s, 30 fps, 30 tbr, 30k tbn, 60k tbc (default)
    Metadata:
      handler_name    : VideoHandler
      encoder         : AVC Coding
Stream mapping:
  Stream #0:0 -> #0:0 (h264 (native) -> mjpeg (native))
Press [q] to stop, [?] for help
[swscaler @ 0x7ff38f02bc00] deprecated pixel format used, make sure you did set range correctly
Output #0, image2, to '/tmp/ActionVLAD-DEMO/frames/image_%05d.jpg':
  Metadata:
    major_brand     : mp42
    minor_version   : 0
    compatible_brands: mp41isom
    encoder         : Lavf57.71.100
    Stream #0:0(und): Video: mjpeg, yuvj420p(pc), 1280x720 [SAR 1:1 DAR 16:9], q=2-31, 200 kb/s, 30 fps, 30 tbn, 30 tbc (default)
    Metadata:
      handler_name    : VideoHandler
      encoder         : Lavc57.89.100 mjpeg
    Side data:
      cpb: bitrate max/min/avg: 0/0/200000 buffer size: 0 vbv_delay: -1
frame=  222 fps=201 q=1.0 Lsize=N/A time=00:00:07.40 bitrate=N/A speed=6.71x    
video:19030kB audio:0kB subtitle:0kB other streams:0kB global headers:0kB muxing overhead: unknown
INFO:tensorflow:Using file /tmp/ActionVLAD-DEMO/lists//test_split1.txt
INFO:tensorflow:Scale of 0 disables regularizer.
INFO:tensorflow:BGR flipping stream 0
INFO:tensorflow:Assuming the batch is full of RGB images, and BGR flipped
INFO:tensorflow:Performing eval pre-processing
INFO:tensorflow:Randomly initializing the (64, 512) netvlad cluster centers
INFO:tensorflow:Scale of 0 disables regularizer.
INFO:tensorflow:Scale of 0 disables regularizer.
INFO:tensorflow:Scale of 0 disables regularizer.
WARNING:tensorflow:From eval_image_classifier.py:278 in main.: streaming_recall_at_k (from tensorflow.contrib.metrics.python.ops.metric_ops) is deprecated and will be removed after 2016-11-08.
Instructions for updating:
Please use `streaming_sparse_recall_at_k`, and reshape labels from [batch_size] to [batch_size, 1].
WARNING:tensorflow:From eval_image_classifier.py:284 in main.: scalar_summary (from tensorflow.python.ops.logging_ops) is deprecated and will be removed after 2016-11-30.
Instructions for updating:
Please switch to tf.summary.scalar. Note that tf.summary.scalar uses the node name instead of the tag. This means that TensorFlow will automatically de-duplicate summary names based on the scope they are created in. Also, passing a tensor or list of tags to a scalar summary op is no longer supported.
WARNING:tensorflow:From eval_image_classifier.py:284 in main.: scalar_summary (from tensorflow.python.ops.logging_ops) is deprecated and will be removed after 2016-11-30.
Instructions for updating:
Please switch to tf.summary.scalar. Note that tf.summary.scalar uses the node name instead of the tag. This means that TensorFlow will automatically de-duplicate summary names based on the scope they are created in. Also, passing a tensor or list of tags to a scalar summary op is no longer supported.
INFO:tensorflow:Evaluating None
INFO:tensorflow:Error reported to Coordinator: <class 'tensorflow.python.framework.errors_impl.InternalError'>, Unable to get element from the feed as bytes.
Traceback (most recent call last):
  File "eval_image_classifier.py", line 357, in <module>
    tf.app.run()
  File "/Users/wuhaoyang/anaconda2/envs/tf_v0.12.0rc0/lib/python2.7/site-packages/tensorflow/python/platform/app.py", line 43, in run
    sys.exit(main(sys.argv[:1] + flags_passthrough))
  File "eval_image_classifier.py", line 330, in main
    saver.restore(sess, checkpoint_path)
  File "/Users/wuhaoyang/anaconda2/envs/tf_v0.12.0rc0/lib/python2.7/site-packages/tensorflow/python/training/saver.py", line 1388, in restore
    {self.saver_def.filename_tensor_name: save_path})
  File "/Users/wuhaoyang/anaconda2/envs/tf_v0.12.0rc0/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 766, in run
    run_metadata_ptr)
  File "/Users/wuhaoyang/anaconda2/envs/tf_v0.12.0rc0/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 964, in _run
    feed_dict_string, options, run_metadata)
  File "/Users/wuhaoyang/anaconda2/envs/tf_v0.12.0rc0/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 1014, in _do_run
    target_list, options, run_metadata)
  File "/Users/wuhaoyang/anaconda2/envs/tf_v0.12.0rc0/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 1034, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.InternalError: Unable to get element from the feed as bytes.
Traceback (most recent call last):
  File "get_class.py", line 7, in <module>
    with h5py.File(sys.argv[1], 'r') as fin, open(sys.argv[2], 'r') as fin2:
  File "/Users/wuhaoyang/anaconda2/envs/tf_v0.12.0rc0/lib/python2.7/site-packages/h5py/_hl/files.py", line 271, in __init__
    fid = make_fid(name, mode, userblock_size, fapl, swmr=swmr)
  File "/Users/wuhaoyang/anaconda2/envs/tf_v0.12.0rc0/lib/python2.7/site-packages/h5py/_hl/files.py", line 101, in make_fid
    fid = h5f.open(name, flags, fapl=fapl)
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper (/private/var/folders/my/m6ynh3bn6tq06h7xr3js0z7r0000gn/T/pip-wdzlRM-build/h5py/_objects.c:2840)
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper (/private/var/folders/my/m6ynh3bn6tq06h7xr3js0z7r0000gn/T/pip-wdzlRM-build/h5py/_objects.c:2798)
  File "h5py/h5f.pyx", line 78, in h5py.h5f.open (/private/var/folders/my/m6ynh3bn6tq06h7xr3js0z7r0000gn/T/pip-wdzlRM-build/h5py/h5f.c:2117)
IOError: Unable to open file (Unable to open file: name = '/tmp/actionvlad-demo/feats.h5', errno = 2, error message = 'no such file or directory', flags = 0, o_flags = 0)

I do not have any experience with tensorflow, so what can I do to fix this?
BTW: I am running the algorithm on a macOS Sierra and 2.7 GHz Intel i5 CPU. Do they make the cut?

**Comment by rohitgirdhar** [comment]
Thanks for your interest in our work!
It looks like the temporary feature file can not be created. Maybe check if you have permission to write `/tmp/ActionVLAD-DEMO/`? If not, change that path in `run.sh` to a path to directory where you have write permissions

**Comment by haoyangwu** [comment]
Hi Rohit, thank for the answer! At least I have a bit clue now.
It looks like the problem may be a bit trickier. Whenever I run run.sh it creates a new 
(MY PATH)/ActionVLAD-DEMO folder, and this new folder always have permission drwxr-xr-x , regardless of the permission of its parent folder. (i.e., the path. Even if I change it to 777)
Is there anything you would recommend to do about it?

**Comment by rohitgirdhar** [comment]
Looking at your logs closely it seems it was not able to read the checkpoint model and so didn't store the features. Did you download the pretrained models through `get_models.sh` first?

**Comment by haoyangwu** [comment]
Yes.The folder ~/models/PreTrained is 7.27 GB in size and contains three other folders: 2-stream-pretrained, ActionVLAD-pretrained, imagenet-trained-CUHK

**Comment by rohitgirdhar** [comment]
My bad, I was pointing the demo script to the training output model. I just updated the `demo/ext_feats.sh` to point to the pre-trained model, so it should work now.
