### ISSUE TITLE
How to save results for a customed dataset?

### ISSUE THREAD

**Issue by ZealACMer** [rohitgirdhar/ActionVLAD#32]
Thank you for your excellent work, my question is how to save .h5 classification results as shown in ActionVLAD/data/hmdb51/final_logits/, thank you so much for you kind help.

**Comment by rohitgirdhar** [comment]
The [example testing script](https://github.com/rohitgirdhar/ActionVLAD/blob/master/experiments/ext_logits.sh) stores features into h5 files. You can also change the layer you want to store.
