### ISSUE TITLE
why split zreo to tensor?

### ISSUE THREAD

**Issue by githubsora** [rohitgirdhar/ActionVLAD#34]
tf.split(0, videos_per_batch, net_normed)

**Comment by githubsora** [comment]
https://github.com/rohitgirdhar/ActionVLAD/blob/0d87b69d3069db3fe521923675e353f755c5d765/nets/frame_pooling.py#L74

**Comment by githubsora** [comment]
https://github.com/rohitgirdhar/ActionVLAD/blob/0d87b69d3069db3fe521923675e353f755c5d765/nets/frame_pooling.py#L73

**Comment by rohitgirdhar** [comment]
As mentioned in the README, the code was developed with TF 0.12 RC0, which followed a [different API](https://github.com/tensorflow/tensorflow/blob/0.12.0-rc0/tensorflow/python/ops/array_ops.py#L1117).
