### ISSUE TITLE
Flow feature vectors

### ISSUE THREAD

**Issue by tsaxena** [rohitgirdhar/ActionVLAD#38]
@rohitgirdhar you mention in the paper that you use 25 frames for both RGB and flows, but then mention that you create an optical flow stack for 10 consercutive x and y displacement images. How did you calculate 10 optical flows from 25 images?

**Comment by rohitgirdhar** [comment]
The 25 frames refer to 25 equally spaced frames from the full video. Let's say they are taken at positions 0, T, 2T, ... of the video.
The frame in case of RGB stream is just the frame at the positions 0, T, 2T etc.
The "frame" in case of flow is the optical flow between consecutive frames at a given position. So at position 0, it involves optical flow between frames 0 and 1, 1 and 2, ..., 8 and 9. All these optical flows are then stacked in the channel dimension, to get one "optical flow frame" at position 0. Similarly, at position T, it will be flow between frame at T and T+1, T+1 and T+2 ..., T+8 and T+9. And so on.
