### ISSUE TITLE
Performance of "rgb+flow" modality?

### ISSUE THREAD

**Issue by hitsx** [rohitgirdhar/ActionVLAD#6]
I noticed that in the datasets/video_data_utils.py file you add a modality of "rgb+flow", and I want to know you motivation of designing this representation, and whether this representation yields a better performance?
Thank you!

**Comment by rohitgirdhar** [comment]
We did try earlier fusion of the RGB and flow features, and hence use that input modality (to make sure the flow and RGB is aligned in time). As table 3(a) in our [paper](https://arxiv.org/pdf/1704.02895.pdf) shows, it didn't do better than late fusion for our case. The motivation was to spatially correlate the visual features with the motion.
