### ISSUE TITLE
large alloc problems

### ISSUE THREAD

**Issue by nehal1985** [rohitgirdhar/ActionVLAD#7]
when i run "bash ext_all_logits.sh"

i get this message while creating flow batches: 
tcmalloc: large alloc 16056549376 bytes == 0x1f3e56000 @ 0x7fb8fedd1c7b 0x7fb8e4d6715f 0x7fb8e5f74348 0x7fb8e5f80cbd 0x7fb8e5fa91da 0x7fb8e5faab91 0x7fb8e60f6899 0x7fb8e60f6f5a 0x7fb8e62dd538 0x7fb8e62dcd00 0x7fb8fd9a9c80 0x7fb8feb896ba 0x7fb8fe8bf3dd (nil)

how can i solve it?

**Comment by rohitgirdhar** [comment]
I think you can just ignore that warning (I assume this doesn't crash the program, right?). You can try to run it without the `tcmalloc` (run it with the standard `malloc` implementation by commenting out [this line](https://github.com/rohitgirdhar/ActionVLAD/blob/00cbc34fa9e65034d9dd733c0d0d081e24794ed0/experiments/ext_logits.sh#L18)) and you won't see this warning.
