### ISSUE TITLE
Could you release the ActionVlad pre-trained model for UCF101?

### ISSUE THREAD

**Issue by xdhhh** [rohitgirdhar/ActionVLAD#9]
Hi!

I am trying to reproduce your performance on UCF101, but cannot make it. So i wonder whether you can release the pre-trained model on UCF101? Thank you so much!

**Comment by cwzat** [comment]
Agree with you!

**Comment by rohitgirdhar** [comment]
Thanks for your interest. I've just added links to UCF101 models into `get_models.sh`. Hope it helps!
